#!/usr/bin/expect -f

set timeout -1

spawn qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb \
    -append "root=/dev/sdc2 panic=1 rootfstype=ext4 ro console=ttyAMA0 console=ttyS0" \
    -drive file=[lindex $argv 1],index=0,media=disk \
    -drive file=[lindex $argv 2],index=1,media=disk \
    -drive file=[lindex $argv 0],index=2,media=disk \
    -monitor none -soundhw all -nographic -serial pty \
    -chardev stdio,id=mon0 -mon chardev=mon0,mode=readline \
    -chardev socket,id=mon1,host=localhost,port=4444,server,nowait \
    -mon chardev=mon1,mode=control,pretty=on \
    -vnc 0.0.0.0:1

expect "System halted."

send "quit\n"
